name: CI Quality Gates

on:
  push:
    branches:
      - main
      - testing-suite
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: TEST_SECRET_KEY  # Used by auth_utils.py

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Start Backend
        run: |
          poetry run uvicorn backend.app.main:app --host 127.0.0.1 --port 8000 &
          sleep 5

      - name: Start Streamlit Frontend
        run: |
          poetry run streamlit run frontend/app.py --server.headless true &
          sleep 5

      - name: Wait for Frontend to be Ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:8501; do
            echo "Waiting for Streamlit to start..."
            sleep 2
          done

      - name: Run Ruff and Flake8
        run: |
          poetry run ruff . --quiet
          poetry run flake8 .

      - name: Run Bandit (Security Static Analysis)
        run: poetry run bandit -r backend -ll

      - name: Run Pytest with Coverage
        run: poetry run pytest --cov=backend/app --cov-report=term-missing --cov-fail-under=80

      - name: Run Mutation Testing
        run: |
          poetry run mutmut run || true

      - name: Run Locust Performance Test
        run: poetry run locust -f tests/perf_test_locust.py --headless --host=http://localhost:8000 -u 5 -r 2 -t 10s || true
